'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("divisi")>
    Partial Public Class DivisiModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fDivisiName As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("divisi_name")>
        Public Property DivisiName() As String
            Get
                Return fDivisiName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DivisiName", fDivisiName, value)
            End Set
        End Property
        <Association("JabatanModelReferencesDivisiModel")>
        Public ReadOnly Property Jabatans() As XPCollection(Of JabatanModel)
            Get
                Return GetCollection(Of JabatanModel)("Jabatans")
            End Get
        End Property
        <Association("KaryawanModelReferencesDivisiModel")>
        Public ReadOnly Property Karyawans() As XPCollection(Of KaryawanModel)
            Get
                Return GetCollection(Of KaryawanModel)("Karyawans")
            End Get
        End Property
    End Class

End Namespace
