'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("jabatan")>
    Partial Public Class JabatanModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fDivisi As DivisiModel
        <Persistent("divisi")>
        <Association("JabatanModelReferencesDivisiModel")>
        Public Property Divisi() As DivisiModel
            Get
                Return fDivisi
            End Get
            Set(ByVal value As DivisiModel)
                SetPropertyValue(Of DivisiModel)("Divisi", fDivisi, value)
            End Set
        End Property
        Dim fJabatanName As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("jabatan_name")>
        Public Property JabatanName() As String
            Get
                Return fJabatanName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("JabatanName", fJabatanName, value)
            End Set
        End Property
        <Association("KaryawanModelReferencesJabatanModel")>
        Public ReadOnly Property Karyawans() As XPCollection(Of KaryawanModel)
            Get
                Return GetCollection(Of KaryawanModel)("Karyawans")
            End Get
        End Property
    End Class

End Namespace
