'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("karyawan")>
    Partial Public Class KaryawanModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNoKtp As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_ktp")>
        Public Property NoKtp() As String
            Get
                Return fNoKtp
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoKtp", fNoKtp, value)
            End Set
        End Property
        Dim fNamaKaryawan As Long
        <Persistent("nama_karyawan")>
        Public Property NamaKaryawan() As Long
            Get
                Return fNamaKaryawan
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("NamaKaryawan", fNamaKaryawan, value)
            End Set
        End Property
        Dim fAlamat As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat")>
        Public Property Alamat() As String
            Get
                Return fAlamat
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Alamat", fAlamat, value)
            End Set
        End Property
        Dim fNoTelepon As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_telepon")>
        Public Property NoTelepon() As String
            Get
                Return fNoTelepon
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoTelepon", fNoTelepon, value)
            End Set
        End Property
        Dim fEmail As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("email")>
        Public Property Email() As String
            Get
                Return fEmail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Email", fEmail, value)
            End Set
        End Property
        Dim fNoHandphone As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_handphone")>
        Public Property NoHandphone() As String
            Get
                Return fNoHandphone
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoHandphone", fNoHandphone, value)
            End Set
        End Property
        Dim fDivisi As DivisiModel
        <Persistent("divisi")>
        <Association("KaryawanModelReferencesDivisiModel")>
        Public Property Divisi() As DivisiModel
            Get
                Return fDivisi
            End Get
            Set(ByVal value As DivisiModel)
                SetPropertyValue(Of DivisiModel)("Divisi", fDivisi, value)
            End Set
        End Property
        Dim fJabatan As JabatanModel
        <Persistent("jabatan")>
        <Association("KaryawanModelReferencesJabatanModel")>
        Public Property Jabatan() As JabatanModel
            Get
                Return fJabatan
            End Get
            Set(ByVal value As JabatanModel)
                SetPropertyValue(Of JabatanModel)("Jabatan", fJabatan, value)
            End Set
        End Property
        Dim fIsactive As Boolean
        <Persistent("isActive")>
        Public Property Isactive() As Boolean
            Get
                Return fIsactive
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Isactive", fIsactive, value)
            End Set
        End Property
        Dim fSpv As KaryawanModel
        <Persistent("spv")>
        <Association("KaryawanModelReferencesKaryawanModel")>
        Public Property Spv() As KaryawanModel
            Get
                Return fSpv
            End Get
            Set(ByVal value As KaryawanModel)
                SetPropertyValue(Of KaryawanModel)("Spv", fSpv, value)
            End Set
        End Property
        Dim fTanggalMasuk As DateTime
        <Persistent("tanggal_masuk")>
        Public Property TanggalMasuk() As DateTime
            Get
                Return fTanggalMasuk
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalMasuk", fTanggalMasuk, value)
            End Set
        End Property
        Dim fTanggalResign As DateTime
        <Persistent("tanggal_resign")>
        Public Property TanggalResign() As DateTime
            Get
                Return fTanggalResign
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalResign", fTanggalResign, value)
            End Set
        End Property
        Dim fKeteranganResign As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("keterangan_resign")>
        Public Property KeteranganResign() As String
            Get
                Return fKeteranganResign
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("KeteranganResign", fKeteranganResign, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("updated_by")>
        Public Property UpdatedBy() As String
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
        Dim fBranch As BranchModel
        <Persistent("branch")>
        <Association("KaryawanModelReferencesBranchModel")>
        Public Property Branch() As BranchModel
            Get
                Return fBranch
            End Get
            Set(ByVal value As BranchModel)
                SetPropertyValue(Of BranchModel)("Branch", fBranch, value)
            End Set
        End Property
        <Association("KaryawanModelReferencesKaryawanModel")>
        Public ReadOnly Property KaryawanModelCollection() As XPCollection(Of KaryawanModel)
            Get
                Return GetCollection(Of KaryawanModel)("KaryawanModelCollection")
            End Get
        End Property
        <Association("UnitProspekModelReferencesKaryawanModel")>
        Public ReadOnly Property UnitProspeks() As XPCollection(Of UnitProspekModel)
            Get
                Return GetCollection(Of UnitProspekModel)("UnitProspeks")
            End Get
        End Property
        <Association("UnitProspekModelReferencesKaryawanModel1")>
        Public ReadOnly Property UnitProspeks1() As XPCollection(Of UnitProspekModel)
            Get
                Return GetCollection(Of UnitProspekModel)("UnitProspeks1")
            End Get
        End Property
        <Association("UserModelReferencesKaryawanModel")>
        Public ReadOnly Property Users() As XPCollection(Of UserModel)
            Get
                Return GetCollection(Of UserModel)("Users")
            End Get
        End Property
    End Class

End Namespace
