'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("menu")>
    Partial Public Class MenuModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fMenuName As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("menu_name")>
        Public Property MenuName() As String
            Get
                Return fMenuName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MenuName", fMenuName, value)
            End Set
        End Property
        Dim fMenuLevel As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("menu_level")>
        Public Property MenuLevel() As String
            Get
                Return fMenuLevel
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MenuLevel", fMenuLevel, value)
            End Set
        End Property
        Dim fParentMenu As Long
        <Persistent("parent_menu")>
        Public Property ParentMenu() As Long
            Get
                Return fParentMenu
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("ParentMenu", fParentMenu, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fCreatedBy As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("created_by")>
        Public Property CreatedBy() As String
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        <Association("RoleMenuModelReferencesMenuModel")>
        Public ReadOnly Property RoleMenus() As XPCollection(Of RoleMenuModel)
            Get
                Return GetCollection(Of RoleMenuModel)("RoleMenus")
            End Get
        End Property
    End Class

End Namespace
