'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("role")>
    Partial Public Class RoleModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fRoleName As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("role_name")>
        Public Property RoleName() As String
            Get
                Return fRoleName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RoleName", fRoleName, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        <Association("RoleMenuModelReferencesRoleModel")>
        Public ReadOnly Property RoleMenus() As XPCollection(Of RoleMenuModel)
            Get
                Return GetCollection(Of RoleMenuModel)("RoleMenus")
            End Get
        End Property
        <Association("UserModelReferencesRoleModel")>
        Public ReadOnly Property Users() As XPCollection(Of UserModel)
            Get
                Return GetCollection(Of UserModel)("Users")
            End Get
        End Property
    End Class

End Namespace
