'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("role_menu")>
    Partial Public Class RoleMenuModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fRoleid As RoleModel
        <Persistent("roleid")>
        <Association("RoleMenuModelReferencesRoleModel")>
        Public Property Roleid() As RoleModel
            Get
                Return fRoleid
            End Get
            Set(ByVal value As RoleModel)
                SetPropertyValue(Of RoleModel)("Roleid", fRoleid, value)
            End Set
        End Property
        Dim fMenuid As MenuModel
        <Persistent("menuid")>
        <Association("RoleMenuModelReferencesMenuModel")>
        Public Property Menuid() As MenuModel
            Get
                Return fMenuid
            End Get
            Set(ByVal value As MenuModel)
                SetPropertyValue(Of MenuModel)("Menuid", fMenuid, value)
            End Set
        End Property
    End Class

End Namespace
