'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_spk")>
    Partial Public Class UnitSpkModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNoSpk As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_spk")>
        Public Property NoSpk() As String
            Get
                Return fNoSpk
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoSpk", fNoSpk, value)
            End Set
        End Property
        Dim fTanggalSpk As DateTime
        <Persistent("tanggal_spk")>
        Public Property TanggalSpk() As DateTime
            Get
                Return fTanggalSpk
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalSpk", fTanggalSpk, value)
            End Set
        End Property
        Dim fCustomer As UnitCustomerModel
        <Persistent("customer")>
        <Association("UnitSpkModelReferencesUnitCustomerModel")>
        Public Property Customer() As UnitCustomerModel
            Get
                Return fCustomer
            End Get
            Set(ByVal value As UnitCustomerModel)
                SetPropertyValue(Of UnitCustomerModel)("Customer", fCustomer, value)
            End Set
        End Property
        Dim fProspek As UnitProspekModel
        <Persistent("prospek")>
        <Association("UnitSpkModelReferencesUnitProspekModel")>
        Public Property Prospek() As UnitProspekModel
            Get
                Return fProspek
            End Get
            Set(ByVal value As UnitProspekModel)
                SetPropertyValue(Of UnitProspekModel)("Prospek", fProspek, value)
            End Set
        End Property
        Dim fModel As UnitModelModel
        <Persistent("model")>
        <Association("UnitSpkModelReferencesUnitModelModel")>
        Public Property Model() As UnitModelModel
            Get
                Return fModel
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("Model", fModel, value)
            End Set
        End Property
        Dim fWarna As UnitWarnaModel
        <Persistent("warna")>
        <Association("UnitSpkModelReferencesUnitWarnaModel")>
        Public Property Warna() As UnitWarnaModel
            Get
                Return fWarna
            End Get
            Set(ByVal value As UnitWarnaModel)
                SetPropertyValue(Of UnitWarnaModel)("Warna", fWarna, value)
            End Set
        End Property
        Dim fRangka As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("rangka")>
        Public Property Rangka() As String
            Get
                Return fRangka
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rangka", fRangka, value)
            End Set
        End Property
        Dim fMesin As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("mesin")>
        Public Property Mesin() As String
            Get
                Return fMesin
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Mesin", fMesin, value)
            End Set
        End Property
        Dim fJenisPenjualan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("jenis_penjualan")>
        Public Property JenisPenjualan() As String
            Get
                Return fJenisPenjualan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("JenisPenjualan", fJenisPenjualan, value)
            End Set
        End Property
        Dim fLeasing As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("leasing")>
        Public Property Leasing() As String
            Get
                Return fLeasing
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Leasing", fLeasing, value)
            End Set
        End Property
        Dim fTenor As Decimal
        <Persistent("tenor")>
        Public Property Tenor() As Decimal
            Get
                Return fTenor
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Tenor", fTenor, value)
            End Set
        End Property
        Dim fStatusSpk As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("status_spk")>
        Public Property StatusSpk() As String
            Get
                Return fStatusSpk
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("StatusSpk", fStatusSpk, value)
            End Set
        End Property
        Dim fHarga As Decimal
        <Persistent("harga")>
        Public Property Harga() As Decimal
            Get
                Return fHarga
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Harga", fHarga, value)
            End Set
        End Property
        Dim fPotongan As Decimal
        <Persistent("potongan")>
        Public Property Potongan() As Decimal
            Get
                Return fPotongan
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Potongan", fPotongan, value)
            End Set
        End Property
        Dim fBranch As BranchModel
        <Persistent("branch")>
        <Association("UnitSpkModelReferencesBranchModel")>
        Public Property Branch() As BranchModel
            Get
                Return fBranch
            End Get
            Set(ByVal value As BranchModel)
                SetPropertyValue(Of BranchModel)("Branch", fBranch, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
    End Class

End Namespace
