'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_customer")>
    Partial Public Class UnitCustomerModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNamaCustomer As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("nama_customer")>
        Public Property NamaCustomer() As String
            Get
                Return fNamaCustomer
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NamaCustomer", fNamaCustomer, value)
            End Set
        End Property
        Dim fAlamat As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat")>
        Public Property Alamat() As String
            Get
                Return fAlamat
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Alamat", fAlamat, value)
            End Set
        End Property
        Dim fNoTelepon As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_telepon")>
        Public Property NoTelepon() As String
            Get
                Return fNoTelepon
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoTelepon", fNoTelepon, value)
            End Set
        End Property
        Dim fKodePos As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("kode_pos")>
        Public Property KodePos() As String
            Get
                Return fKodePos
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("KodePos", fKodePos, value)
            End Set
        End Property
        Dim fKotakabupaten As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("kotaKabupaten")>
        Public Property Kotakabupaten() As String
            Get
                Return fKotakabupaten
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Kotakabupaten", fKotakabupaten, value)
            End Set
        End Property
        Dim fPekerjaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("pekerjaan")>
        Public Property Pekerjaan() As String
            Get
                Return fPekerjaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Pekerjaan", fPekerjaan, value)
            End Set
        End Property
        Dim fDetailPekerjaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("detail_pekerjaan")>
        Public Property DetailPekerjaan() As String
            Get
                Return fDetailPekerjaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DetailPekerjaan", fDetailPekerjaan, value)
            End Set
        End Property
        Dim fPerusahaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("perusahaan")>
        Public Property Perusahaan() As String
            Get
                Return fPerusahaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Perusahaan", fPerusahaan, value)
            End Set
        End Property
        Dim fAlamatPerusahaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat_perusahaan")>
        Public Property AlamatPerusahaan() As String
            Get
                Return fAlamatPerusahaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AlamatPerusahaan", fAlamatPerusahaan, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
        <Association("UnitSpkModelReferencesUnitCustomerModel")>
        Public ReadOnly Property UnitSpks() As XPCollection(Of UnitSpkModel)
            Get
                Return GetCollection(Of UnitSpkModel)("UnitSpks")
            End Get
        End Property
    End Class

End Namespace
