'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_prospek")>
    Partial Public Class UnitProspekModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNamaProspek As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("nama_prospek")>
        Public Property NamaProspek() As String
            Get
                Return fNamaProspek
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NamaProspek", fNamaProspek, value)
            End Set
        End Property
        Dim fAlamat As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat")>
        Public Property Alamat() As String
            Get
                Return fAlamat
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Alamat", fAlamat, value)
            End Set
        End Property
        Dim fNoTelepon As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_telepon")>
        Public Property NoTelepon() As String
            Get
                Return fNoTelepon
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoTelepon", fNoTelepon, value)
            End Set
        End Property
        Dim fKodePos As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("kode_pos")>
        Public Property KodePos() As String
            Get
                Return fKodePos
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("KodePos", fKodePos, value)
            End Set
        End Property
        Dim fKotakabupaten As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("kotaKabupaten")>
        Public Property Kotakabupaten() As String
            Get
                Return fKotakabupaten
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Kotakabupaten", fKotakabupaten, value)
            End Set
        End Property
        Dim fStatusInformasi As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("status_informasi")>
        Public Property StatusInformasi() As String
            Get
                Return fStatusInformasi
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("StatusInformasi", fStatusInformasi, value)
            End Set
        End Property
        Dim fModel As UnitModelModel
        <Persistent("model")>
        <Association("UnitProspekModelReferencesUnitModelModel")>
        Public Property Model() As UnitModelModel
            Get
                Return fModel
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("Model", fModel, value)
            End Set
        End Property
        Dim fWarna As UnitWarnaModel
        <Persistent("warna")>
        <Association("UnitProspekModelReferencesUnitWarnaModel")>
        Public Property Warna() As UnitWarnaModel
            Get
                Return fWarna
            End Get
            Set(ByVal value As UnitWarnaModel)
                SetPropertyValue(Of UnitWarnaModel)("Warna", fWarna, value)
            End Set
        End Property
        Dim fSales As KaryawanModel
        <Persistent("sales")>
        <Association("UnitProspekModelReferencesKaryawanModel1")>
        Public Property Sales() As KaryawanModel
            Get
                Return fSales
            End Get
            Set(ByVal value As KaryawanModel)
                SetPropertyValue(Of KaryawanModel)("Sales", fSales, value)
            End Set
        End Property
        Dim fSalesHead As KaryawanModel
        <Persistent("sales_head")>
        <Association("UnitProspekModelReferencesKaryawanModel")>
        Public Property SalesHead() As KaryawanModel
            Get
                Return fSalesHead
            End Get
            Set(ByVal value As KaryawanModel)
                SetPropertyValue(Of KaryawanModel)("SalesHead", fSalesHead, value)
            End Set
        End Property
        Dim fTanggalInput As DateTime
        <Persistent("tanggal_input")>
        Public Property TanggalInput() As DateTime
            Get
                Return fTanggalInput
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalInput", fTanggalInput, value)
            End Set
        End Property
        Dim fTanggalProspek As DateTime
        <Persistent("tanggal_prospek")>
        Public Property TanggalProspek() As DateTime
            Get
                Return fTanggalProspek
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalProspek", fTanggalProspek, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
        Dim fPekerjaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("pekerjaan")>
        Public Property Pekerjaan() As String
            Get
                Return fPekerjaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Pekerjaan", fPekerjaan, value)
            End Set
        End Property
        Dim fDetailPekerjaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("detail_pekerjaan")>
        Public Property DetailPekerjaan() As String
            Get
                Return fDetailPekerjaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DetailPekerjaan", fDetailPekerjaan, value)
            End Set
        End Property
        Dim fPerusahaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("perusahaan")>
        Public Property Perusahaan() As String
            Get
                Return fPerusahaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Perusahaan", fPerusahaan, value)
            End Set
        End Property
        Dim fAlamatPerusahaan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat_perusahaan")>
        Public Property AlamatPerusahaan() As String
            Get
                Return fAlamatPerusahaan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AlamatPerusahaan", fAlamatPerusahaan, value)
            End Set
        End Property
        Dim fSumberData As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("sumber_data")>
        Public Property SumberData() As String
            Get
                Return fSumberData
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SumberData", fSumberData, value)
            End Set
        End Property
        Dim fJenisPenjualan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("jenis_penjualan")>
        Public Property JenisPenjualan() As String
            Get
                Return fJenisPenjualan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("JenisPenjualan", fJenisPenjualan, value)
            End Set
        End Property
        Dim fTestDrive As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("test_drive")>
        Public Property TestDrive() As String
            Get
                Return fTestDrive
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TestDrive", fTestDrive, value)
            End Set
        End Property
        Dim fLeasing As Long
        <Persistent("leasing")>
        Public Property Leasing() As Long
            Get
                Return fLeasing
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Leasing", fLeasing, value)
            End Set
        End Property
        Dim fTenor As Long
        <Persistent("tenor")>
        Public Property Tenor() As Long
            Get
                Return fTenor
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Tenor", fTenor, value)
            End Set
        End Property
        Dim fJumlahUnit As Decimal
        <Persistent("jumlah_unit")>
        Public Property JumlahUnit() As Decimal
            Get
                Return fJumlahUnit
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("JumlahUnit", fJumlahUnit, value)
            End Set
        End Property
        <Association("UnitProspekFollowupModelReferencesUnitProspekModel")>
        Public ReadOnly Property UnitProspekFollowups() As XPCollection(Of UnitProspekFollowupModel)
            Get
                Return GetCollection(Of UnitProspekFollowupModel)("UnitProspekFollowups")
            End Get
        End Property
        <Association("UnitSpkModelReferencesUnitProspekModel")>
        Public ReadOnly Property UnitSpks() As XPCollection(Of UnitSpkModel)
            Get
                Return GetCollection(Of UnitSpkModel)("UnitSpks")
            End Get
        End Property
    End Class

End Namespace
