'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_purchase_detail")>
    Partial Public Class UnitPurchaseDetailModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fPembelian As UnitPurchaseModel
        <Persistent("pembelian")>
        <Association("UnitPurchaseDetailModelReferencesUnitPurchaseModel")>
        Public Property Pembelian() As UnitPurchaseModel
            Get
                Return fPembelian
            End Get
            Set(ByVal value As UnitPurchaseModel)
                SetPropertyValue(Of UnitPurchaseModel)("Pembelian", fPembelian, value)
            End Set
        End Property
        Dim fModel As UnitModelModel
        <Persistent("model")>
        <Association("UnitPurchaseDetailModelReferencesUnitModelModel")>
        Public Property Model() As UnitModelModel
            Get
                Return fModel
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("Model", fModel, value)
            End Set
        End Property
        Dim fNilai As Decimal
        <Persistent("nilai")>
        Public Property Nilai() As Decimal
            Get
                Return fNilai
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Nilai", fNilai, value)
            End Set
        End Property
        Dim fPotongan As Decimal
        <Persistent("potongan")>
        Public Property Potongan() As Decimal
            Get
                Return fPotongan
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Potongan", fPotongan, value)
            End Set
        End Property
        Dim fDpp As Decimal
        <Persistent("dpp")>
        Public Property Dpp() As Decimal
            Get
                Return fDpp
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Dpp", fDpp, value)
            End Set
        End Property
        Dim fPpn As Decimal
        <Persistent("ppn")>
        Public Property Ppn() As Decimal
            Get
                Return fPpn
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Ppn", fPpn, value)
            End Set
        End Property
        Dim fTotal As Decimal
        <Persistent("total")>
        Public Property Total() As Decimal
            Get
                Return fTotal
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Total", fTotal, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        <Association("UnitReceiveModelReferencesUnitPurchaseDetailModel")>
        Public ReadOnly Property UnitReceives() As XPCollection(Of UnitReceiveModel)
            Get
                Return GetCollection(Of UnitReceiveModel)("UnitReceives")
            End Get
        End Property
    End Class

End Namespace
