'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_receive")>
    Partial Public Class UnitReceiveModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fUnitPembelian As UnitPurchaseDetailModel
        <Indexed(Name:="iunit_pembelian_unit_receive")>
        <Persistent("unit_pembelian")>
        <Association("UnitReceiveModelReferencesUnitPurchaseDetailModel")>
        Public Property UnitPembelian() As UnitPurchaseDetailModel
            Get
                Return fUnitPembelian
            End Get
            Set(ByVal value As UnitPurchaseDetailModel)
                SetPropertyValue(Of UnitPurchaseDetailModel)("UnitPembelian", fUnitPembelian, value)
            End Set
        End Property
        Dim fSuratJalan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("surat_jalan")>
        Public Property SuratJalan() As String
            Get
                Return fSuratJalan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SuratJalan", fSuratJalan, value)
            End Set
        End Property
        Dim fTanggalDiterima As DateTime
        <Persistent("tanggal_diterima")>
        Public Property TanggalDiterima() As DateTime
            Get
                Return fTanggalDiterima
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalDiterima", fTanggalDiterima, value)
            End Set
        End Property
        Dim fGudang As UnitGudangModel
        <Persistent("gudang")>
        <Association("UnitReceiveModelReferencesUnitGudangModel")>
        Public Property Gudang() As UnitGudangModel
            Get
                Return fGudang
            End Get
            Set(ByVal value As UnitGudangModel)
                SetPropertyValue(Of UnitGudangModel)("Gudang", fGudang, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
        Dim fModel As UnitModelModel
        <Persistent("model")>
        <Association("UnitReceiveModelReferencesUnitModelModel")>
        Public Property Model() As UnitModelModel
            Get
                Return fModel
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("Model", fModel, value)
            End Set
        End Property
        Dim fWarna As UnitWarnaModel
        <Persistent("warna")>
        <Association("UnitReceiveModelReferencesUnitWarnaModel")>
        Public Property Warna() As UnitWarnaModel
            Get
                Return fWarna
            End Get
            Set(ByVal value As UnitWarnaModel)
                SetPropertyValue(Of UnitWarnaModel)("Warna", fWarna, value)
            End Set
        End Property
        Dim fTahun As String
        <Size(255)>
        <Persistent("tahun")>
        Public Property Tahun() As String
            Get
                Return fTahun
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Tahun", fTahun, value)
            End Set
        End Property
        Dim fNoRangka As String
        <Size(255)>
        <Persistent("no_rangka")>
        Public Property NoRangka() As String
            Get
                Return fNoRangka
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoRangka", fNoRangka, value)
            End Set
        End Property
        Dim fNoMesin As String
        <Size(255)>
        <Persistent("no_mesin")>
        Public Property NoMesin() As String
            Get
                Return fNoMesin
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoMesin", fNoMesin, value)
            End Set
        End Property
        Dim fNoFaktur As String
        <Size(255)>
        <Persistent("no_faktur")>
        Public Property NoFaktur() As String
            Get
                Return fNoFaktur
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoFaktur", fNoFaktur, value)
            End Set
        End Property
        Dim fNoKunci As String
        <Size(255)>
        <Persistent("no_kunci")>
        Public Property NoKunci() As String
            Get
                Return fNoKunci
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoKunci", fNoKunci, value)
            End Set
        End Property
        Dim fKeterangan As String
        <Size(255)>
        <Persistent("keterangan")>
        Public Property Keterangan() As String
            Get
                Return fKeterangan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Keterangan", fKeterangan, value)
            End Set
        End Property
    End Class

End Namespace
