'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_accessory")>
    Partial Public Class UnitAccessoryModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNamaAccessory As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("nama_accessory")>
        Public Property NamaAccessory() As String
            Get
                Return fNamaAccessory
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NamaAccessory", fNamaAccessory, value)
            End Set
        End Property
        Dim fKeterangan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("keterangan")>
        Public Property Keterangan() As String
            Get
                Return fKeterangan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Keterangan", fKeterangan, value)
            End Set
        End Property
        Dim fStatus As Boolean
        <Persistent("status")>
        Public Property Status() As Boolean
            Get
                Return fStatus
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Status", fStatus, value)
            End Set
        End Property
        <Association("UnitAccessoryModelModelReferencesUnitAccessoryModel")>
        Public ReadOnly Property UnitAccessoryModels() As XPCollection(Of UnitAccessoryModelModel)
            Get
                Return GetCollection(Of UnitAccessoryModelModel)("UnitAccessoryModels")
            End Get
        End Property
    End Class

End Namespace
