'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_stock")>
    Partial Public Class UnitStockModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fModel As UnitModelModel
        <Persistent("model")>
        <Association("UnitStockModelReferencesUnitModelModel")>
        Public Property Model() As UnitModelModel
            Get
                Return fModel
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("Model", fModel, value)
            End Set
        End Property
        Dim fWarna As UnitWarnaModel
        <Persistent("warna")>
        <Association("UnitStockModelReferencesUnitWarnaModel")>
        Public Property Warna() As UnitWarnaModel
            Get
                Return fWarna
            End Get
            Set(ByVal value As UnitWarnaModel)
                SetPropertyValue(Of UnitWarnaModel)("Warna", fWarna, value)
            End Set
        End Property
        Dim fRangka As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("rangka")>
        Public Property Rangka() As String
            Get
                Return fRangka
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rangka", fRangka, value)
            End Set
        End Property
        Dim fMesin As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("mesin")>
        Public Property Mesin() As String
            Get
                Return fMesin
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Mesin", fMesin, value)
            End Set
        End Property
        Dim fTahun As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("tahun")>
        Public Property Tahun() As String
            Get
                Return fTahun
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Tahun", fTahun, value)
            End Set
        End Property
        Dim fGudang As UnitGudangModel
        <Persistent("gudang")>
        <Association("UnitStockModelReferencesUnitGudangModel")>
        Public Property Gudang() As UnitGudangModel
            Get
                Return fGudang
            End Get
            Set(ByVal value As UnitGudangModel)
                SetPropertyValue(Of UnitGudangModel)("Gudang", fGudang, value)
            End Set
        End Property
        Dim fTanggalMasuk As DateTime
        <Persistent("tanggal_masuk")>
        Public Property TanggalMasuk() As DateTime
            Get
                Return fTanggalMasuk
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalMasuk", fTanggalMasuk, value)
            End Set
        End Property
        Dim fTanggalKeluar As DateTime
        <Persistent("tanggal_keluar")>
        Public Property TanggalKeluar() As DateTime
            Get
                Return fTanggalKeluar
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalKeluar", fTanggalKeluar, value)
            End Set
        End Property
        Dim fHargaBeli As Decimal
        <Persistent("harga_beli")>
        Public Property HargaBeli() As Decimal
            Get
                Return fHargaBeli
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("HargaBeli", fHargaBeli, value)
            End Set
        End Property
        Dim fHargaJual As Decimal
        <Persistent("harga_jual")>
        Public Property HargaJual() As Decimal
            Get
                Return fHargaJual
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("HargaJual", fHargaJual, value)
            End Set
        End Property
        Dim fStatus As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("status")>
        Public Property Status() As String
            Get
                Return fStatus
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Status", fStatus, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
    End Class

End Namespace
