'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_supplier")>
    Partial Public Class UnitSupplierModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fNamaSupplier As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("nama_supplier")>
        Public Property NamaSupplier() As String
            Get
                Return fNamaSupplier
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NamaSupplier", fNamaSupplier, value)
            End Set
        End Property
        Dim fAlamat As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("alamat")>
        Public Property Alamat() As String
            Get
                Return fAlamat
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Alamat", fAlamat, value)
            End Set
        End Property
        Dim fKota As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("kota")>
        Public Property Kota() As String
            Get
                Return fKota
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Kota", fKota, value)
            End Set
        End Property
        Dim fNoTelepon As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("no_telepon")>
        Public Property NoTelepon() As String
            Get
                Return fNoTelepon
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NoTelepon", fNoTelepon, value)
            End Set
        End Property
        Dim fNpwp As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("npwp")>
        Public Property Npwp() As String
            Get
                Return fNpwp
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Npwp", fNpwp, value)
            End Set
        End Property
        Dim fNamaNpwp As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("nama_npwp")>
        Public Property NamaNpwp() As String
            Get
                Return fNamaNpwp
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NamaNpwp", fNamaNpwp, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
        <Association("UnitPurchaseModelReferencesUnitSupplierModel")>
        Public ReadOnly Property UnitPurchases() As XPCollection(Of UnitPurchaseModel)
            Get
                Return GetCollection(Of UnitPurchaseModel)("UnitPurchases")
            End Get
        End Property
        <Association("UnitPurchaseReturnModelReferencesUnitSupplierModel")>
        Public ReadOnly Property UnitPurchaseReturns() As XPCollection(Of UnitPurchaseReturnModel)
            Get
                Return GetCollection(Of UnitPurchaseReturnModel)("UnitPurchaseReturns")
            End Get
        End Property
    End Class

End Namespace
