'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_receive")>
    Partial Public Class UnitReceiveModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fUnitPembelian As UnitPurchaseDetailModel
        <Persistent("unit_pembelian")>
        <Association("UnitReceiveModelReferencesUnitPurchaseDetailModel")>
        Public Property UnitPembelian() As UnitPurchaseDetailModel
            Get
                Return fUnitPembelian
            End Get
            Set(ByVal value As UnitPurchaseDetailModel)
                SetPropertyValue(Of UnitPurchaseDetailModel)("UnitPembelian", fUnitPembelian, value)
            End Set
        End Property
        Dim fSuratJalan As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("surat_jalan")>
        Public Property SuratJalan() As String
            Get
                Return fSuratJalan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SuratJalan", fSuratJalan, value)
            End Set
        End Property
        Dim fTanggalDiterima As DateTime
        <Persistent("tanggal_diterima")>
        Public Property TanggalDiterima() As DateTime
            Get
                Return fTanggalDiterima
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TanggalDiterima", fTanggalDiterima, value)
            End Set
        End Property
        Dim fGudang As UnitGudangModel
        <Persistent("gudang")>
        <Association("UnitReceiveModelReferencesUnitGudangModel")>
        Public Property Gudang() As UnitGudangModel
            Get
                Return fGudang
            End Get
            Set(ByVal value As UnitGudangModel)
                SetPropertyValue(Of UnitGudangModel)("Gudang", fGudang, value)
            End Set
        End Property
        Dim fCreatedBy As Long
        <Persistent("created_by")>
        Public Property CreatedBy() As Long
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedAt As DateTime
        <Persistent("created_at")>
        Public Property CreatedAt() As DateTime
            Get
                Return fCreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fCreatedAt, value)
            End Set
        End Property
        Dim fUpdatedBy As Long
        <Persistent("updated_by")>
        Public Property UpdatedBy() As Long
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedAt As DateTime
        <Persistent("updated_at")>
        Public Property UpdatedAt() As DateTime
            Get
                Return fUpdatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedAt", fUpdatedAt, value)
            End Set
        End Property
    End Class

End Namespace
