'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("unit_accessory_model")>
    Partial Public Class UnitAccessoryModelModel
        Inherits XPLiteObject
        Dim fId As Short
        <Key()>
        <Persistent("id")>
        Public Property Id() As Short
            Get
                Return fId
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("Id", fId, value)
            End Set
        End Property
        Dim fUnitId As UnitModelModel
        <Persistent("unit_id")>
        <Association("UnitAccessoryModelModelReferencesUnitModelModel")>
        Public Property UnitId() As UnitModelModel
            Get
                Return fUnitId
            End Get
            Set(ByVal value As UnitModelModel)
                SetPropertyValue(Of UnitModelModel)("UnitId", fUnitId, value)
            End Set
        End Property
        Dim fAccId As UnitAccessoryModel
        <Persistent("acc_id")>
        <Association("UnitAccessoryModelModelReferencesUnitAccessoryModel")>
        Public Property AccId() As UnitAccessoryModel
            Get
                Return fAccId
            End Get
            Set(ByVal value As UnitAccessoryModel)
                SetPropertyValue(Of UnitAccessoryModel)("AccId", fAccId, value)
            End Set
        End Property
    End Class

End Namespace
