'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace HDMS

    <Persistent("user")>
    Partial Public Class UserModel
        Inherits XPLiteObject
        Dim fId As Long
        <Key(True)>
        <Persistent("id")>
        Public Property Id() As Long
            Get
                Return fId
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Id", fId, value)
            End Set
        End Property
        Dim fUsername As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("username")>
        Public Property Username() As String
            Get
                Return fUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Username", fUsername, value)
            End Set
        End Property
        Dim fPersonName As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("person_name")>
        Public Property PersonName() As String
            Get
                Return fPersonName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PersonName", fPersonName, value)
            End Set
        End Property
        Dim fPassword As String
        <Size(SizeAttribute.Unlimited)>
        <Persistent("password")>
        Public Property Password() As String
            Get
                Return fPassword
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Password", fPassword, value)
            End Set
        End Property
        Dim fRole As RoleModel
        <Persistent("role")>
        <Association("UserModelReferencesRoleModel")>
        Public Property Role() As RoleModel
            Get
                Return fRole
            End Get
            Set(ByVal value As RoleModel)
                SetPropertyValue(Of RoleModel)("Role", fRole, value)
            End Set
        End Property
        Dim fKaryawan As KaryawanModel
        <Persistent("karyawan")>
        <Association("UserModelReferencesKaryawanModel")>
        Public Property Karyawan() As KaryawanModel
            Get
                Return fKaryawan
            End Get
            Set(ByVal value As KaryawanModel)
                SetPropertyValue(Of KaryawanModel)("Karyawan", fKaryawan, value)
            End Set
        End Property
        Dim fIsactive As Boolean
        <Persistent("isActive")>
        Public Property Isactive() As Boolean
            Get
                Return fIsactive
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Isactive", fIsactive, value)
            End Set
        End Property
    End Class

End Namespace
